export default [
  "Chuck Norris is intimidated by you",
  "daily commuters appreciate the way you signal in advance",
  "doctors boast about the perfection that exudes from your gallbladder",
  "even the sound of church bells cannot beat the purity that exits your mouth during karaoke",
  "everyone at sleepovers thought you were the bravest during thunderstorms",
  "if friendships were donuts, you'd be the sprinkle kind, full of colour and wonder",
  "loved ones say your smile is as joyful as the cool spot found on a pillow",
  "marine biologists imagine your heart to be as beautiful as the echo of a whale during mating season",
  "people behind you at movies think you are the perfect height",
  "photographers believe you could make a fortune in the modelling industry even without the need for filters and Photoshop",
  "sushi chefs are wowed by your chopstick dexterity",
  "the only thing that shines brighter than you is the Sun, and only by a little bit",
  "truck drivers are grateful for your generosity in allowing them to merge onto the highway",
  "your speech reaches the masses like wind chimes spreading nature's song",
  "your stride is as graceful as a skateboard on smooth terrain",
];
