export default [
  "Chuck Norris is intimidated by you",
  "I appreciate you",
  "I bet you do the crossword puzzle in ink",
  "I bet you make babies smile",
  "I bet you sweat glitter",
  "I like your style",
  "actions speak louder than words, and yours tell an incredible story",
  "any team would be lucky to have you on it",
  "babies and small animals probably love you",
  "being around you is like being on a happy little vacation",
  "being around you makes everything better",
  "colors seem brighter when you're around",
  "daily commuters appreciate the way you signal in advance",
  "doctors boast about the perfection that exudes from your gallbladder",
  "even the sound of church bells cannot beat the purity that exits your mouth during karaoke",
  "everyone at sleepovers thought you were the bravest during thunderstorms",
  "everyone gets knocked down sometimes, but you always get back up and keep going",
  "everything would be better if more people were like you",
  "hanging out with you is always a blast",
  "has anyone ever told you that you have great posture",
  "how do you keep being so funny and making everyone laugh",
  "how is it that you always look great, even in sweatpants",
  "if cartoon bluebirds were real, a bunch of them would be sitting on your shoulders singing right now",
  "if friendships were donuts, you'd be the sprinkle kind, full of colour and wonder",
  "if someone based an Internet meme on you, it would have impeccable grammar",
  "if you were a box of crayons, you'd be the giant name-brand one with the built-in sharpener",
  "if you were a scented candle they'd call it Perfectly Imperfect (and it would smell like summer)",
  "in high school I bet you were voted 'most likely to keep being awesome.",
  "is that your picture next to 'charming' in the dictionary",
  "jokes are funnier when you tell them",
  "loved ones say your smile is as joyful as the cool spot found on a pillow",
  "marine biologists imagine your heart to be as beautiful as the echo of a whale during mating season",
  "on a scale from 1 to 10, you're an 11",
  "our community is better because you're in it",
  "people behind you at movies think you are the perfect height",
  "photographers believe you could make a fortune in the modelling industry even without the need for filters and Photoshop",
  "somehow you make time stop and fly at the same time",
  "someone is getting through something hard right now because you've got their back",
  "sushi chefs are wowed by your chopstick dexterity",
  "that color is perfect on you",
  "that thing you don't like about yourself is what makes you so interesting",
  "the only thing that shines brighter than you is the Sun, and only by a little bit",
  "the people you love are lucky to have you in their lives",
  "the way you treasure your loved ones is incredible",
  "there's ordinary, and then there's you",
  "truck drivers are grateful for your generosity in allowing them to merge onto the highway",
  "when you make a mistake, you fix it",
  "when you make up your mind about something, nothing stands in your way",
  "when you say, 'I meant to do that,' I totally believe you",
  "when you're not afraid to be yourself is when you're most incredible",
  "who raised you? They deserve a medal for a job well done",
  "you always know -- and say -- exactly what I need to hear when I need to hear it",
  "you always know how to find that silver lining",
  "you always know just what to say",
  "you are brave",
  "you are enough",
  "you are making a difference",
  "you are the most perfect you there is",
  "you bring out the best in other people",
  "you could survive a Zombie apocalypse",
  "you deserve a hug right now",
  "you have a good head on your shoulders",
  "you have a great sense of humor",
  "you have impeccable manners",
  "you have the best ideas",
  "you have the best laugh",
  "you have the courage of your convictions",
  "you light up the room",
  "you look great today",
  "you may dance like no one's watching, but everyone's watching because you're an amazing dancer",
  "you seem to really know who you are",
  "you should be proud of yourself",
  "you should be thanked more often. So thank you!",
  "you smell really good",
  "you were cool way before hipsters were cool",
  "you're a candle in the darkness",
  "you're a gift to those around you",
  "you're a great example to others",
  "you're a great listener",
  "you're a smart cookie",
  "you're all that and a super-size bag of chips",
  "you're always learning new things and trying to better yourself, which is awesome",
  "you're an awesome friend",
  "you're better than a triple-scoop ice cream cone. With sprinkles",
  "you're even better than a unicorn, because you're real",
  "you're even more beautiful on the inside than you are on the outside",
  "you're gorgeous -- and that's the least interesting thing about you, too",
  "you're great at figuring stuff out",
  "you're inspiring",
  "you're irresistible when you blush",
  "you're like a breath of fresh air",
  "you're like sunshine on a rainy day",
  "you're more fun than a ball pit filled with candy",
  "you're more fun than bubble wrap",
  "you're more helpful than you realize",
  "you're one of a kind",
  "you're really something special",
  "you're so thoughtful",
  "you're someone's reason to smile",
  "you're strong",
  "you're wonderful",
  "you've got all the right moves",
  "your ability to recall random factoids at just the right time is impressive",
  "your bellybutton is kind of adorable",
  "your creative potential seems limitless",
  "your eyes are breathtaking",
  "your hair looks stunning",
  "your kindness is a balm to all who encounter it",
  "your name suits you to a T",
  "your perspective is refreshing",
  "your smile is contagious",
  "your speech reaches the masses like wind chimes spreading nature's song",
  "your stride is as graceful as a skateboard on smooth terrain",
  "your voice is magnificent",
];
