export default [
  "all of your ideas are boring",
  "I am utterly annoyed by your wit",
  "I disagree with anyone who agrees with you",
  "I dislike the way you move",
  "I dislike your Facebook status",
  "I dislike your jacket",
  "I dislike your socks",
  "I don't appreciate all of your opinions",
  "I don't enjoy spending time with you",
  "I don't like your haircut",
  "I dont' feel the need to impress you",
  "I feel like you hung the projector screen too high",
  "I find you very irrelevant",
  "I hate what you've done with the place",
  "I hate your style",
  "I made a website to mock you",
  "I really dislike the way you pronounce the word 'ruby'",
  "I would hate a roadtrip with you",
  "I wouldn't share my dessert with you",
  "I'm sorry we met",
  "nobody trusts you",
  "that looks bad on you",
  "what an ugly sweater",
  "when I grow up, I want to be the opposite of you",
  "when you do not distribute an agenda prior to the meeting, the participants do not come prepared",
  "you are not charming",
  "you bore me",
  "you don't deserve a compliment!",
  "you don't deserve a promotion",
  "you get an F",
  "you have a poor taste in websites",
  "you have a poor web-surfing stance",
  "you have imperfect bone structure",
  "you haven't earned a break",
  "you only care about yourself. You are completely self absorbed",
  "you seem to make a lot of careless errors",
  "you would look bad in glasses OR contacts",
  "you're average",
  "you're not invited to my birthday party",
  "you're not smart!",
  "you're predictable, and I hate it",
  "your cooking is worse than my mother's",
  "your life is so boring",
  "you need to stop leaving the Cheerios out",
];
