const criticisms = [
  "When you do not distribute an agenda prior to the meeting, the participants do not come prepared",
  "Nobody trusts you",
  "You only care about yourself. You are completely self absorbed",
  "You seem to make a lot of careless errors",
  "I feel like you hung the projector screen too high",
  "you need to stop leaving the Cheerios out",
  "I don't like your haircut",
  "You don't deserve a promotion",
  "What an ugly sweater",
  "I don't appreciate all of your opinions",
  "I hate your style",
  "I hate what you've done with the place",
  "I am utterly annoyed by your wit",
  "I really dislike the way you pronounce the word 'ruby'",
  "I dislike your Facebook status",
  "That looks bad on you",
  "You have a poor taste in websites",
  "I dislike your jacket",
  "I dislike the way you move",
  "You have a poor web-surfing stance",
  "You have imperfect bone structure",
  "I disagree with anyone who agrees with you",
  "I dislike your socks",
  "You are not charming",
  "Your cooking is worse than my mother's",
  "You're average",
  "You don't deserve a compliment!",
  "You haven't earned a break",
  "Your life is so boring",
  "I don't enjoy spending time with you",
  "I wouldn't share my dessert with you",
  "You're not invited to my birthday party",
  "All of your ideas are boring",
  "You're predictable, and I hate it",
  "You get an F",
  "I would hate a roadtrip with you",
  "You would look bad in glasses OR contacts",
  "I dont' feel the need to impress you",
  "I'm sorry we met",
  "You're not smart!",
  "I made a website to mock you",
  "When I grow up, I want to be the opposite of you",
  "I find you very irrelevant",
  "You bore me",
];

module.exports = criticisms;
